### ISSUE TITLE
Moc děkuji, funguje to!

### ISSUE THREAD

**Issue by CodicManiac** [jasomtubratu/HeroHeroDownloader#3]
Moc děkuji, funguje to!

**Comment by jasomtubratu** [comment]
Čauko!
Takto nefungujú Github Issues. Pokiaľ sa ti repository páči, úplne stačí tomu dať hviezdu (vedľa forku). 
Issues sa vytvárajú, pokiaľ nastala nejaká chyba v tomto programe.

Každopádne ďakujem, tento issue uzatváram!
